language: java
before_install:
  - sudo apt-get install libc6-dev-i386
  - sudo apt-get install lib32ncurses5-dev
  - sudo apt-get install libx11-dev
  - sudo apt-get install g++-multilib
  - sudo apt-get install lib32z1-dev
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - android update sdk --filter tools,platform-tools,android-16 --no-ui --no-https -a
install:
  - sudo pip install python-swiftclient
script: 
  - mvn clean install -DTRAVIS=true
